# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Bob-Linux

on:
  workflow_call:
    inputs:
      configuration:
        description: "Build configuration"
        required: true
        default: "Release"
        type: string
      build_dir:
        description: "Build directory"
        required: false
        default: "build"
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.build.outputs.path }}
    steps:
      # Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install CMake and dependencies
        run: |
          sudo apt update -y;
          wget https://apt.llvm.org/llvm.sh; chmod +x llvm.sh; sudo ./llvm.sh 20;
          sudo apt install vim net-tools tmux cmake git libjsoncpp-dev build-essential cmake uuid-dev libhiredis-dev zlib1g-dev unzip -y;

      # Configure the project
      - name: Configure with CMake
        run: |
          cmake -S . -B ${{ inputs.build_dir }} \
            -DCMAKE_BUILD_TYPE=${{ inputs.configuration }} \
            -DCMAKE_C_COMPILER=clang-20 \
            -DCMAKE_CXX_COMPILER=clang++-20

      # Build the project
      - name: Build with Make
        run: cmake --build ${{ inputs.build_dir }} --config ${{ inputs.configuration }} -- -j$(nproc)

      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BobLinuxBuild-${{ inputs.configuration }}
          path: |
            ${{ inputs.build_dir }}
